In [54]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import networkx as nx

In [55]:
nodes = pd.read_csv('cleaned_top_ingreds.csv')
nodes = nodes.drop('Unnamed: 0', axis=1)
edges = pd.read_csv('filtered_pairs.csv')
edges = edges.drop('Unnamed: 0', axis=1)

In [56]:
print(nodes.shape, edges.shape)

(196, 3) (17833, 4)

In [57]:
edges.head()

,pairs,counts,ingred1,ingred2
0,"('all-purpose flour', 'almond')",657,all-purpose flour,almond
1,"('all-purpose flour', 'almond extract')",634,all-purpose flour,almond extract
2,"('all-purpose flour', 'apple')",356,all-purpose flour,apple
3,"('all-purpose flour', 'avocado')",53,all-purpose flour,avocado
4,"('all-purpose flour', 'bacon')",411,all-purpose flour,bacon

In [58]:
edges.groupby('ingred1').agg({'counts':'sum'}).join(edges.groupby('ingred2').agg({'counts':'sum'}), lsuffix='1', rsuffix='2').fillna(0)

                       counts1   counts2
ingred1
all-purpose flour       174402       0.0
almond                   13679     713.0
almond extract            7040     894.0
apple                     6823     424.0
avocado                   8845     157.0
bacon                    15531     519.0
baking powder            61186    7509.0
baking soda              47410    8608.0
balsamic vinegar         16520     374.0
banana                    5145     757.0
basil                    33227    1148.0
bay leaf                 39745    1496.0
beef broth                6623     590.0
bittersweet chocolate     7631     950.0
black bean                9339     435.0
black olive               6084     496.0
black peppercorn         12853    1204.0
blue cheese               3984     420.0
bread crumb              19626    1401.0
brown sugar              75389   11869.0
butter                  233111   48236.0
buttermilk               15016    6760.0
butternut squash          4067     663.0
cake flour                7194    2804.0
cake mix                  3177     587.0
canola oil               30557    5181.0
caper                     8722    1216.0
carrot                   45593    7890.0
cayenne                   5624    1096.0
celery                   31383    8740.0
...                        ...       ...
shortening                2043    6746.0
shrimp                    2016   10533.0
smith apple               1270    5282.0
sour cream                6351   32261.0
soy sauce                 5375   30903.0
spanish onion              859    5507.0
sugar                    35160  216397.0
sweet onion                665    4891.0
sweet potato               951    8480.0
thyme                     4599   49590.0
tomato                    3364   34613.0
tomato juice               759    5645.0
tomato paste              1644   18940.0
tomato sauce               829   10798.0
vanilla                    432    9408.0
vanilla bean               907    9203.0
vanilla extract           5342   99750.0
vegetable oil             4322   84782.0
walnut                     419   20894.0
wheat flour                164    5198.0
whipping cream             373   14044.0
white onion                612   10696.0
white rice                 322    8741.0
white vinegar              334   11938.0
white wine                 597   35730.0
whole clove                141    6445.0
whole milk                 127   26392.0
wine vinegar               425   39162.0
worcestershire sauce        44   24937.0
zucchini                    30   14688.0

[196 rows x 2 columns]

In [59]:
len(list(set(list(edges['ingred1'].unique()) + list(edges['ingred2'].unique()))))

196